services:
  caddy:
    container_name: caddy
    build:
      context: ./docker/caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/www
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000'
    volumes:
      - ./:/www
